name: 发布新文章
description: 通过 Gist 链接发布一篇新的 Markdown 文章
title: "新文章发布"
labels: ["new-article"]
body:
  - type: markdown
    attributes:
      value: |
        ## 发布新文章
        请在下方填入包含文章内容的 GitHub Gist 链接。

  - type: input
    id: gist_url
    attributes:
      label: Gist 链接
      description: 填入包含 Markdown 文章的 Gist URL
      placeholder: "https://gist.github.com/username/xxxxx"
    validations:
      required: true
